meta_product_name: "Gather Go"
meta_title: "Gather Go - Planning made simple. Party made epic! "
meta_description: "Your personal party generator."
meta_image: "cover.png" # should exist in `app/assets/images/`
